Style/AsciiComments:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Layout/HashAlignment:
  Enabled: false
