default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Qna_development
  username: <%= Rails.application.credentials[Rails.env.to_sym][:database][:username] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:database][:password] %>

test:
  <<: *default
  database: Qna_test
  username: <%= Rails.application.credentials[Rails.env.to_sym][:database][:username] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:database][:password] %>

production:
  <<: *default
  database: qna_production
  username: <%= Rails.application.credentials[Rails.env.to_sym][:database][:username] %>
  password: '<%= Rails.application.credentials[Rails.env.to_sym][:database][:password] %>'
  pool: 20
